apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}
  labels: {{- include "helm.labels" . | nindent 4 }}
  annotations:
    cloud.google.com/network-tier: standard
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: 3333
      protocol: TCP
      name: https
    - port: 80
      targetPort: 3333
      protocol: TCP
      name: http
  selector: { { - include "helm.selectorLabels" . | nindent 4 } }
